apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: frontend-mcs
spec:
  template:
    spec:
      selector:
        app: frontend
      ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080